// Date: 7/24/2014 2:17:44 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.raizunne.miscellany.client.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class modelQuantBottom extends ModelBase
{
  //fields
    ModelRenderer X1;
    ModelRenderer X2;
    ModelRenderer X3;
    ModelRenderer Corner1;
    ModelRenderer Corner2;
    ModelRenderer Corner3;
    ModelRenderer Corner4;
  
  public modelQuantBottom()
  {
    textureWidth = 64;
    textureHeight = 64;
    
      X1 = new ModelRenderer(this, 0, 0);
      X1.addBox(0F, 0F, 0F, 8, 16, 14);
      X1.setRotationPoint(-4F, 0F, -7F);
      X1.setTextureSize(64, 64);
      X1.mirror = true;
      setRotation(X1, 0F, 0F, 0F);
      X2 = new ModelRenderer(this, 0, 30);
      X2.addBox(0F, 0F, 0F, 3, 16, 8);
      X2.setRotationPoint(4F, 0F, -4F);
      X2.setTextureSize(64, 64);
      X2.mirror = true;
      setRotation(X2, 0F, 0F, 0F);
      X3 = new ModelRenderer(this, 0, 30);
      X3.addBox(0F, 0F, 0F, 3, 16, 8);
      X3.setRotationPoint(-7F, 0F, -4F);
      X3.setTextureSize(64, 64);
      X3.mirror = true;
      setRotation(X3, 0F, 0F, 0F);
      Corner1 = new ModelRenderer(this, 44, 0);
      Corner1.addBox(1F, 0F, -4F, 3, 16, 2);
      Corner1.setRotationPoint(-4F, 0F, -0.5F);
      Corner1.setTextureSize(64, 64);
      Corner1.mirror = true;
      setRotation(Corner1, 0F, 0.7853982F, 0F);
      Corner2 = new ModelRenderer(this, 44, 0);
      Corner2.addBox(-0.1F, 0F, -1.5F, 3, 16, 2);
      Corner2.setRotationPoint(3F, 0F, -5F);
      Corner2.setTextureSize(64, 64);
      Corner2.mirror = true;
      setRotation(Corner2, 0F, -0.7853982F, 0F);
      Corner3 = new ModelRenderer(this, 44, 0);
      Corner3.addBox(0F, 0F, -2F, 3, 16, 2);
      Corner3.setRotationPoint(4F, 0F, 6F);
      Corner3.setTextureSize(64, 64);
      Corner3.mirror = true;
      setRotation(Corner3, 0F, 0.7853982F, 0F);
      Corner4 = new ModelRenderer(this, 44, 0);
      Corner4.addBox(0F, 0F, -2F, 3, 16, 2);
      Corner4.setRotationPoint(-6F, 0F, 4F);
      Corner4.setTextureSize(64, 64);
      Corner4.mirror = true;
      setRotation(Corner4, 0F, -0.7853982F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    X1.render(f5);
    X2.render(f5);
    X3.render(f5);
    Corner1.render(f5);
    Corner2.render(f5);
    Corner3.render(f5);
    Corner4.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
