// Date: 7/24/2014 1:33:54 AM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX
package com.raizunne.miscellany.client.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelFoodPackager extends ModelBase
{
  //fields
    ModelRenderer Shape1;
    ModelRenderer Shape2;
    ModelRenderer Shape3;
    ModelRenderer Shape4;
    ModelRenderer Left;
    ModelRenderer Shape5;
    ModelRenderer Shape6;
    ModelRenderer Other;
  
  public ModelFoodPackager()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      Shape1 = new ModelRenderer(this, 0, 0);
      Shape1.addBox(0F, 0F, 0F, 10, 16, 6);
      Shape1.setRotationPoint(-5F, 0F, -1F);
      Shape1.setTextureSize(64, 32);
      Shape1.mirror = true;
      setRotation(Shape1, 0F, 0F, 0F);
      Shape2 = new ModelRenderer(this, 32, 0);
      Shape2.addBox(0F, 0F, 0F, 10, 13, 4);
      Shape2.setRotationPoint(-5F, 3F, -5F);
      Shape2.setTextureSize(64, 32);
      Shape2.mirror = true;
      setRotation(Shape2, 0F, 0F, 0F);
      Shape3 = new ModelRenderer(this, 0, 22);
      Shape3.addBox(0F, 0F, 0F, 10, 3, 5);
      Shape3.setRotationPoint(-5F, 3F, -5F);
      Shape3.setTextureSize(64, 32);
      Shape3.mirror = true;
      setRotation(Shape3, 0.6457718F, 0F, 0F);
      Shape4 = new ModelRenderer(this, 30, 23);
      Shape4.addBox(0F, 0F, 0F, 6, 6, 1);
      Shape4.setRotationPoint(-3F, 8F, -6F);
      Shape4.setTextureSize(64, 32);
      Shape4.mirror = true;
      setRotation(Shape4, 0F, 0F, 0F);
      Left = new ModelRenderer(this, 37, 17);
      Left.addBox(0F, 0F, 0F, 1, 5, 1);
      Left.setRotationPoint(-4F, 9F, -6F);
      Left.setTextureSize(64, 32);
      Left.mirror = true;
      setRotation(Left, 0F, 0F, 0F);
      Shape5 = new ModelRenderer(this, 32, 17);
      Shape5.addBox(0F, 0F, 0F, 1, 5, 1);
      Shape5.setRotationPoint(3F, 9F, -6F);
      Shape5.setTextureSize(64, 32);
      Shape5.mirror = true;
      setRotation(Shape5, 0F, 0F, 0F);
      Shape6 = new ModelRenderer(this, 42, 18);
      Shape6.addBox(0F, 0F, 0F, 4, 1, 3);
      Shape6.setRotationPoint(-2F, 1F, -5F);
      Shape6.setTextureSize(64, 32);
      Shape6.mirror = true;
      setRotation(Shape6, 0F, 0F, 0F);
      Other = new ModelRenderer(this, 48, 26);
      Other.addBox(0F, 0F, 0F, 6, 1, 1);
      Other.setRotationPoint(-3F, 2F, -5F);
      Other.setTextureSize(64, 32);
      Other.mirror = true;
      setRotation(Other, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    Shape1.render(f5);
    Shape2.render(f5);
    Shape3.render(f5);
    Shape4.render(f5);
    Left.render(f5);
    Shape5.render(f5);
    Shape6.render(f5);
    Other.render(f5);
  }
  
  public void renderModel(float f){
	  Shape1.render(f);
	  Shape2.render(f);
	  Shape3.render(f);
	  Shape4.render(f);
	  Left.render(f);
	  Shape5.render(f);
	  Shape6.render(f);
	  Other.render(f);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
